-- Origin Income V8.9 — run once in Supabase SQL Editor
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  chosen_plan text,
  payment_status text not null default 'unpaid',
  access_status text not null default 'locked',
  stripe_customer_id text,
  stripe_session_id text unique,
  selected_business_model text,
  purchase_date timestamptz,
  last_payment timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  stripe_session_id text unique not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_customer_id text,
  plan text not null,
  amount_total bigint,
  currency text,
  payment_status text,
  selected_business_model text,
  purchased_at timestamptz not null default now()
);

create table if not exists public.stripe_events (
  event_id text primary key,
  event_type text not null,
  processing_note text,
  processed_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.payments enable row level security;
alter table public.stripe_events enable row level security;

create policy "Users can view own profile" on public.profiles for select using (auth.uid() = user_id);
create policy "Users can view own payments" on public.payments for select using (auth.uid() = user_id);
-- No client policy for stripe_events. Only the Supabase secret key may access it.
