"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Phase={n:number;eyebrow:string;title:string;promise:string;lessons:string[];tasks:string[];deliverable:string;tools:string[]};
const phases:Phase[]=[
{n:1,eyebrow:"FOUNDATION",title:"Fundament & Positionierung",promise:"Definiere eine klare Nische, ein konkretes Problem und ein Angebot, das Unternehmen sofort verstehen.",lessons:["Was eine AI Automation Agency wirklich verkauft","Die richtige Nische statt ‘KI für alle’","Probleme mit messbarem Business-Impact finden","Dein erstes klar formuliertes Automation-Angebot"],tasks:["Wähle 1 Zielbranche","Notiere 5 wiederkehrende Prozesse dieser Branche","Bewerte jeden Prozess nach Zeitersparnis, Umsatzhebel und Umsetzbarkeit","Formuliere dein erstes Angebot in einem Satz"],deliverable:"Deine Positionierung + erstes Kernangebot",tools:["ChatGPT","Notion","Google Sheets"]},
{n:2,eyebrow:"OFFER",title:"Angebot & Zielkunde",promise:"Baue aus deiner Positionierung ein kaufbares Paket mit klarem Ergebnis, Preislogik und idealem Kundenprofil.",lessons:["Ideal Customer Profile","Outcome statt Technik verkaufen","Pilot, Setup Fee und Retainer","Risiko für den ersten Kunden reduzieren"],tasks:["Erstelle dein ICP","Definiere 3 messbare Outcomes","Baue Starter-Angebot und Premium-Angebot","Lege Pilotpreis und Zielpreis fest"],deliverable:"Verkaufsfähiges Angebot + ICP",tools:["Origin Templates","ChatGPT","Canva"]},
{n:3,eyebrow:"SYSTEM",title:"Automation Stack & KI-Tools",promise:"Baue einen schlanken Tech-Stack und deine erste funktionierende Automation ohne unnötige Tool-Kosten.",lessons:["Trigger, Logik, Aktion – das Grundprinzip","Make vs. Zapier vs. n8n","LLMs sinnvoll integrieren","Datenschutz und menschliche Kontrolle"],tasks:["Wähle deinen Automation-Stack","Baue einen Test-Workflow","Füge Fehlerbehandlung hinzu","Dokumentiere Input, Output und Nutzen"],deliverable:"1 funktionierende Demo-Automation",tools:["Make","n8n","OpenAI API","Airtable"]},
{n:4,eyebrow:"PROOF",title:"Demo-System & Portfolio",promise:"Verwandle Technik in sichtbaren Business-Nutzen, den ein Interessent in wenigen Minuten versteht.",lessons:["Demo statt leere Versprechen","Vorher/Nachher visualisieren","Loom-Demo strukturieren","Case Study ohne Fake-Resultate"],tasks:["Erstelle eine Branchen-Demo","Nimm ein 2–4 Min. Demo-Video auf","Erstelle eine One-Page Case Study","Baue deinen Demo-Link"],deliverable:"Portfolio-Demo + Case Study",tools:["Loom","Canva","Notion","Vercel"]},
{n:5,eyebrow:"ACQUISITION",title:"Leads & Kundengewinnung",promise:"Starte ein tägliches Akquise-System, das relevante Unternehmen erreicht statt wahllos Nachrichten zu senden.",lessons:["Leadlisten mit Kaufwahrscheinlichkeit","Personalisierte Cold Outreach","LinkedIn, E-Mail und Telefon kombinieren","Follow-up als System"],tasks:["Baue eine Liste mit 50 Zielkunden","Erstelle 2 Outreach-Skripte","Kontaktiere die ersten 10 Leads","Plane 3 Follow-ups pro Lead"],deliverable:"Aktive Pipeline mit ersten Gesprächen",tools:["LinkedIn","Google Maps","Apollo optional","Gmail"]},
{n:6,eyebrow:"SALES & DELIVERY",title:"Verkauf, Preise & Delivery",promise:"Führe Discovery Calls, schliesse sauber ab und liefere dein Projekt mit professionellem Scope.",lessons:["Discovery statt Pitch-Marathon","ROI und Preis argumentieren","Scope und Change Requests","Onboarding, Test und Übergabe"],tasks:["Erstelle Discovery-Fragen","Baue dein Angebotstemplate","Definiere Delivery-Meilensteine","Erstelle Kunden-Onboarding"],deliverable:"Kompletter Sales- & Delivery-Prozess",tools:["Google Meet","Stripe","Notion","DocuSign optional"]},
{n:7,eyebrow:"SCALE",title:"Retainer, Prozesse & Skalierung",promise:"Mache aus Einzelprojekten wiederkehrende Umsätze und aus deiner Arbeit ein reproduzierbares System.",lessons:["Maintenance Retainer","Monitoring und Support","SOPs und Delegation","Von Service zu produktisiertem Angebot"],tasks:["Definiere 2 Retainer-Pakete","Erstelle Monitoring-Checkliste","Dokumentiere deine SOPs","Setze dein 90-Tage-Wachstumsziel"],deliverable:"Skalierbares Agency-Betriebssystem",tools:["Notion","Slack","Make/n8n","Stripe"]}
];
export default function JourneyClient({firstName,plan}:{firstName:string;plan:string}){
 const key="origin_ai_automation_progress";
 const [active,setActive]=useState(1); const [done,setDone]=useState<Record<string,boolean>>({});
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(key)||"{}");setDone(x.done||{});setActive(x.active||1)}catch{}},[]);
 const completed=Object.values(done).filter(Boolean).length,total=phases.reduce((a,p)=>a+p.tasks.length,0),pct=Math.round(completed/total*100);
 const phase=phases[active-1]; const phaseDone=phase.tasks.every((_,i)=>done[`${active}-${i}`]);
 function toggle(i:number){const next={...done,[`${active}-${i}`]:!done[`${active}-${i}`]};setDone(next);localStorage.setItem(key,JSON.stringify({done:next,active}));}
 function open(n:number){setActive(n);localStorage.setItem(key,JSON.stringify({done,active:n}));window.scrollTo({top:0,behavior:"smooth"});}
 return <main className="journeyShell">
  <aside className="journeySide"><Link href="/dashboard" className="journeyLogo"><span>O</span> ORIGIN <b>INCOME</b></Link><div className="journeySideLabel">BUSINESS JOURNEY</div><h2>AI Automation<br/>Agency</h2><div className="journeyProgress"><div><span>Gesamtfortschritt</span><b>{pct}%</b></div><i><em style={{width:`${pct}%`}}/></i><small>{completed} von {total} Aufgaben abgeschlossen</small></div><nav>{phases.map(p=>{const count=p.tasks.filter((_,i)=>done[`${p.n}-${i}`]).length;return <button key={p.n} className={active===p.n?"active":""} onClick={()=>open(p.n)}><span>{String(p.n).padStart(2,"0")}</span><div><small>{p.eyebrow}</small><b>{p.title}</b></div><em>{count}/{p.tasks.length}</em></button>})}</nav><Link href="/dashboard" className="journeyBack">← Zurück zum Dashboard</Link></aside>
  <section className="journeyMain"><header><div><span className="journeyLive"/> JOURNEY ACTIVE · {plan.toUpperCase()}</div><span>Phase {active} / 7</span></header><div className="journeyContent">
   <div className="journeyHero"><div><small>PHASE {String(active).padStart(2,"0")} · {phase.eyebrow}</small><h1>{phase.title}</h1><p>{phase.promise}</p></div><div className="journeyScore"><strong>{phase.tasks.filter((_,i)=>done[`${active}-${i}`]).length}/{phase.tasks.length}</strong><span>AUFGABEN</span></div></div>
   <div className="journeyGrid"><article className="journeyCard"><div className="journeyCardHead"><span>01</span><div><small>WISSEN</small><h3>Was du in dieser Phase lernst</h3></div></div><div className="lessonList">{phase.lessons.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p><b>→</b></div>)}</div></article>
   <article className="journeyCard taskCard"><div className="journeyCardHead"><span>02</span><div><small>EXECUTION</small><h3>Deine Aufgaben</h3></div></div><p className="taskIntro">Nicht nur lesen. Umsetzen. Hake jede Aufgabe ab, sobald du sie wirklich erledigt hast.</p><div className="journeyTasks">{phase.tasks.map((x,i)=><button key={x} className={done[`${active}-${i}`]?"done":""} onClick={()=>toggle(i)}><i>{done[`${active}-${i}`]?"✓":""}</i><span><small>AUFGABE {i+1}</small>{x}</span></button>)}</div></article></div>
   <div className="journeyBottom"><article><small>DEIN ERGEBNIS</small><h3>{phase.deliverable}</h3><p>Wenn du diese Phase abschliesst, besitzt du ein konkretes Asset für den nächsten Schritt – nicht nur Theorie.</p></article><article><small>EMPFOHLENER STACK</small><div className="toolPills">{phase.tools.map(t=><span key={t}>{t}</span>)}</div><p>Origin AI wird später direkt in dieser Journey neben deinen Aufgaben verfügbar sein.</p></article></div>
   <div className="journeyNext"><div>{phaseDone?<><span>✓ PHASE BEREIT</span><b>Alle Aufgaben dieser Phase sind erledigt.</b></>:<><span>DEIN NÄCHSTER SCHRITT</span><b>Schliesse die {phase.tasks.length-phase.tasks.filter((_,i)=>done[`${active}-${i}`]).length} offenen Aufgaben ab.</b></>}</div>{active<7?<button disabled={!phaseDone} onClick={()=>open(active+1)}>Phase {active+1} starten →</button>:<button disabled={!phaseDone}>Journey abschliessen ✓</button>}</div>
  </div></section>
 </main>
}
